version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "commentator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-thni1p8llm7z"
s3_prefix = "commentator"
region = "ap-northeast-1"
profile = "localmaster"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
